version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::067599918611:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-Y0KICJ8CGC3K"
permissions_provider = "AWS IAM"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::067599918611:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1HL9HYQL1TC1C"
cloudformation_execution_role = "arn:aws:iam::067599918611:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-13SU3W2QY6A3E"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-zufz0m8ce1ts"
image_repository = ""
region = "us-east-2"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::067599918611:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-1KXR7H535G5O1"
cloudformation_execution_role = "arn:aws:iam::067599918611:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-1GB8V446ZZPLA"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-iaht6nkt20f3"
image_repository = ""
region = "us-east-2"
